[package]
name = "render"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { workspace = true }
futures = { workspace = true }
winit = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }
